### ISSUE TITLE
Tests seem to be broken

### ISSUE THREAD

**Issue by kpoeck** [gwkkwg/trivial-backtrace#10]
The tests in https://github.com/gwkkwg/trivial-backtrace/blob/master/test/tests.lisp seem to be broken:
* probably https://github.com/gwkkwg/trivial-backtrace/blob/master/test/tests.lisp#L19 should read :`(addtest (generates-backtrace)`
* why should 
`(with-output-to-string (stream)
		       (print-backtrace c :output nil))`
return a string? Print-backtrace returns a strings, nothing is printed, so the result is ""

**Comment by gwkkwg** [comment]
Thanks for your fixes. I'm not longer doing Lisp development. If trivial-backtrace interests you, I'd be happy to turn the project over to you.
